name: Build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install GNURadio
        run: |
         sudo add-apt-repository ppa:gnuradio/gnuradio-releases
         sudo apt update
         sudo apt install gnuradio-dev
         sudo apt install cmake libsndfile-dev
      - name: Build
        run: |
         cmake -B build
         cmake --build build
